#!/usr/bin/bash

CFLAGS="-g --coverage -fprofile-arcs -ftest-coverage -I ../src "

# Make a build directory
rm -rf build
mkdir build
cd build

# Copy "auto-generated code into the build directory"
cp ../autogenerated_file.c fct3.c

# Compile
gcc -c ../src/fct1.c      ${CFLAGS}
gcc -c        fct3.c      ${CFLAGS}
gcc -c ../external/fct4.c ${CFLAGS}
ar -crs staticlib.a fct1.o fct3.o fct4.o

# Compile and link test code
gcc -o testcode ../src/test/testfct1.c staticlib.a ${CFLAGS}

# Run test
./testcode

# See  https://github.com/gcovr/gcovr/issues/323 - how to get rid of
#   files from       Add exclude pattern     Status
#   ------------     ----------------------  ---------------------
#   build/*          -e "(.*/)*build/"       does NOT WORK
#   src/test/*       -e "(.*/)*src/test/"    works
#   external         -e "(.*/)*external/"    works
gcovr -r .. --object-directory=. --html --html-details -o index.html

echo "check build/index.html for gcovr output using gcovr 4.2"

